import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@uploadthing/react/styles.css";
import "../globals.css";
import { Footer, Navbar } from "../_components/navbarandfooter";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<div className=" flex flex-col flex-wrap gap-6 w-full">
  <Navbar/>
    {children}
    <Footer/>
</div>
    
  );
}
