import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });


 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user =true
//   const user = await currentUser() as User | any 
// const dbuser = await GetUser(user)  
return (
    <ClerkProvider>
<html lang="en">
      <body className={inter.className}>
      {user === undefined || null   ? 
(redirect("/sign-up") ):(
 <>
   {children}
   </> 
)}
        </body>
    </html>
    </ClerkProvider>
  );
}
