import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { auth, currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { GetUser } from "@/lib/action/action.user";
import { User } from "@prisma/client";
const inter = Inter({ subsets: ["latin"] });
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
 
import { ourFileRouter } from "../app/(auth)/api/uploadthing/core";
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user =true
//   const user = await currentUser() as User | any 
// const dbuser = await GetUser(user)  
return (
    <ClerkProvider>
<html lang="en">
      <body className={inter.className}>
      {user === undefined || null   ? 
(redirect("/sign-up") ):(
 <>
  <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        /> 
   {children}
   </> 
)}
        </body>
    </html>
    </ClerkProvider>
  );
}
